tenant_name_prefix: ''
tenant_name_suffix: ''

filter_name_prefix: ''
filter_name_suffix: ''

entry_name_prefix: ''
entry_name_suffix: ''

contract_name_prefix: ''
contract_name_suffix: ''

subject_name_prefix: ''
subject_name_suffix: ''
subject_default_action: 'permit'
subject_default_reverse_filter_port: 'yes'