---
- name: Process filter for tenant {{ tenant.name }}
  include_tasks: wrapper_api_call.yml

  vars:
    payload: "{{ lookup('template', 'filter.json.j2') }}"
    path: "/api/mo/uni/tn-{{ tenant.name }}.json"
    dn: "/api/mo/uni/tn-{{ tenant.name }}/flt-{{ filter.name }}"
    filter_name: "{{ filter_name_prefix ~ filter.name ~ filter_name_suffix }}"

  loop: "{{ tenant.filters | default([]) }}"
  loop_control:
    loop_var: filter
    label: "{{ [ tenant.name, filter.name ] | join('/') }}"

  when:
    - filter.state is defined