---
- set_fact:
    aci_cred: &aci_login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      annotation: orchestrator:ansible
  no_log: true

- name: Processing filter
  aci_rest:
    <<: *aci_login
    method: post
    path: "/api/mo/uni/tn-{{ tenant.name}}.json"
    content: "{{ lookup('template', 'filter.json.j2') | from_yaml | to_json }}"

  delegate_to: localhost
  loop: "{{ tenant.filters | default([]) }}"
  loop_control:
    loop_var: filter
    label: "{{ [ tenant.name, filter.name ] | join('/') }}"
  vars:
    filter_name: "{{ filter_name_prefix ~ filter.name ~ filter_name_suffix }}"
  when:
    - filter.state is defined