---
- name: Process Leaf Profile
  include_tasks: wrapper_api_call.yml

  vars:
    path: "/api/node/mo/uni/infra.json"
    payload: "{{ lookup('template', 'leaf_prof.json.j2') }}"
    dn: "/api/node/mo/uni/infra/nprof-{{ leaf_prof.name }}"

  loop: "{{ leaf_profiles }}"
  loop_control:
    loop_var: leaf_prof
    label: "{{ leaf_prof.name }}"

  when:
    - leaf_prof.state is defined

  no_log: true
