---
- name: Import Leaf Profile Tasks
  include_tasks: leaf_prof.yml
  when: import_leaf_prof_task

- name: Import Leaf Interface Profile Tasks
  include_tasks: leaf_intf_prof.yml
  when: import_leaf_intf_prof_task

- name: Import interface policy tasks
  include_tasks: intf_pol.yml
  when: import_intf_pol_task

- name: Import VLAN Pool tasks
  include_tasks: vlan_pool.yml
  when: import_vlan_pool_task

- name: Import Domain tasks
  include_tasks: domain.yml
  when: import_dom_task

- name: Import AAEP tasks
  include_tasks: aaep.yml
  when: import_aaep_task

- name: Import interface policy groups tasks
  include_tasks: ipg.yml
  when: import_ipg_task
