---
- set_fact:
    async_jobs: []
    domain_type_map:
      physical: phys
      external: l3dom
      virtual: vmm

# - name: Import interface policies tasks
#   include_tasks: intf_policies.yml

- name: Import interface policy  tasks
  include_tasks: intf_pol.yml

# - name: Import interface policy groups tasks
#   include_tasks: ipg.yml

# - name: Import domains tasks
#   include_tasks: domains.yml
#   loop: "{{ domains | dict2items  }}"
#   loop_control:
#     loop_var: domain_vars
#     label: "{{ domain_vars.key }}"
